import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
import type { Metadata } from "next";
import { PropsWithChildren } from "react";
import { Open_Sans } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import NavBar from "@/app/nav-bar";
import AuthProvider from "@/app/auth-provider";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={openSans.variable}>
        <AuthProvider>
          <Theme accentColor="violet" appearance="light">
            <NavBar />
            <main className="container m-auto p-5">{children}</main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
